from fastapi import FastAPI, BackgroundTasks, Request
from pydantic import BaseModel
import uvicorn

from db.schema import init_db, SessionLocal, TradeProposal
from agents.workflow import trading_agent_app
from agents.state import AgentState
from core.telegram_bot import send_telegram_trade_proposal
from core.validator import pre_execution_validation
from core.config import settings
from kiteconnect import KiteConnect
import requests

app = FastAPI(title="AI Trading Agent")

init_db()

class ScanRequest(BaseModel):
    symbol: str

def run_agent_workflow(symbol: str):
    """
    Kicks off the autonomous research loop.
    """
    initial_state = AgentState(
        symbol=symbol,
        messages=[],
        technical_analysis=None,
        fundamental_analysis=None,
        sentiment_analysis=None,
        macro_context=None,
        rl_context=None,
        decision=None,
        is_safe_to_execute=None,
        guardrail_warnings=None
    )
    
    print(f"\n[ORCHESTRATOR] Starting AI Agent Analysis for {symbol}...")
    final_output = trading_agent_app.invoke(initial_state)
    
    # Extract the Pydantic RiskDecision object generated by the LLM
    decision = final_output.get("decision")
    warnings = final_output.get("guardrail_warnings", "")
    
    if not decision:
        print("[ORCHESTRATOR] Node failed to produce a RiskDecision. Aborting.")
        return
        
    session = SessionLocal()
    proposal = TradeProposal(
        symbol=symbol,
        direction=decision.proposed_action,
        proposed_price=decision.proposed_entry,
        stop_loss=decision.proposed_stop_loss,
        take_profit=decision.proposed_take_profit,
        rationale=decision.final_rationale + f"\n\nGuardrails: {warnings}",
        status="PENDING" if final_output.get("is_safe_to_execute") else "ABORTED_BY_GUARDRAIL"
    )
    session.add(proposal)
    session.commit()
    session.refresh(proposal)
    print(f"\n[ORCHESTRATOR] Analysis Complete: {symbol}. Agent decided to {decision.proposed_action}.")
    
    # Send for human approval if it's a BUY or SELL
    if proposal.direction in ["BUY", "SELL"]:
        send_telegram_trade_proposal(
            proposal_id=proposal.id,
            symbol=proposal.symbol,
            action=proposal.direction,
            rationale=proposal.rationale,
            entry=proposal.proposed_price,
            sl=proposal.stop_loss,
            tp=proposal.take_profit,
            holding_days=decision.expected_holding_days
        )
    session.close()

@app.post("/scan")
async def trigger_scan(req: ScanRequest, bg_tasks: BackgroundTasks):
    """ API to manually trigger the agent to scan a symbol """
    bg_tasks.add_task(run_agent_workflow, req.symbol)
    return {"message": f"Agent dispatched to scan {req.symbol} in the background."}

@app.post("/telegram-webhook")
async def telegram_webhook(request: Request):
    """ Receives the Approve/Reject callbacks from Telegram """
    payload = await request.json()

    if "callback_query" in payload:
        callback_data = payload["callback_query"]["data"]
        callback_id = payload["callback_query"]["id"]  # Used to stop the loading icon

        # e.g. "APPROVE_1"
        action, prop_id_str = callback_data.split("_")
        proposal_id = int(prop_id_str)

        # STOP THE TELEGRAM LOADING SPINNER immediately
        requests.post(
            f"https://api.telegram.org/bot{settings.TELEGRAM_BOT_TOKEN}/answerCallbackQuery",
            json={"callback_query_id": callback_id, "text": f"Processing: {action}..."}
        )

        session = SessionLocal()
        proposal = session.query(TradeProposal).filter(TradeProposal.id == proposal_id).first()

        if not proposal or proposal.status != "PENDING":
            session.close()
            return {"status": "ok", "message": "Already processed or invalid."}

        if action == "REJECT":
            proposal.status = "REJECTED"
            print(f"[Webhook] User REJECTED trade {proposal_id}")

        elif action == "APPROVE":
            print(f"[Webhook] User APPROVED trade {proposal_id}. Re-validating price...")

            # PRE-EXECUTION VALIDATION: ensure price hasn't drifted
            is_safe = pre_execution_validation(proposal.symbol, proposal.proposed_price)
            if is_safe:
                print(f"[Webhook] Guardrails Passed! Sending {proposal.direction} order to Zerodha for {proposal.symbol}...")

                try:
                    kite = KiteConnect(api_key=settings.KITE_API_KEY)
                    kite.set_access_token(settings.KITE_ACCESS_TOKEN)

                    # Dynamic variety and product from strategy config
                    strategy_trad = settings.strategy.get("trading", {})
                    order_variety = strategy_trad.get("order_variety", "AMO").lower()
                    
                    # Map variety string to Kite constant
                    variety = kite.VARIETY_AMO if order_variety == "amo" else kite.VARIETY_REGULAR
                    product = getattr(kite, f"PRODUCT_{strategy_trad.get('product_type', 'CNC').upper()}")
                    quantity = strategy_trad.get("default_quantity", 1)

                    order_id = kite.place_order(
                        tradingsymbol=proposal.symbol,
                        exchange=kite.EXCHANGE_NSE,
                        transaction_type=kite.TRANSACTION_TYPE_BUY if proposal.direction == "BUY" else kite.TRANSACTION_TYPE_SELL,
                        quantity=quantity,
                        variety=variety,
                        order_type=kite.ORDER_TYPE_LIMIT,
                        product=product,
                        price=proposal.proposed_price
                    )
                    # Only mark EXECUTED after Kite confirms the order
                    proposal.status = "EXECUTED"
                    print(f"✅ SUCCESS! EXECUTED on Kite. LIVE Order ID: {order_id}")

                except Exception as e:
                    # Leave status as PENDING so user can retry on next signal
                    proposal.status = "KITE_FAILED"
                    print(f"❌ KITE EXECUTION FAILED: {e}")
            else:
                proposal.status = "ABORTED"
                print(f"[Webhook] Trade {proposal_id} ABORTED. Price drifted outside safe zone.")

        session.commit()
        session.close()

    return {"status": "ok"}

if __name__ == "__main__":
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)

